# This is a basic workflow to help you get started with Actions

name: Testing

env:
  DOTNET_VERSION: '6.0.x'
  FRAMEWORK_PROJECT_PATH: src/SwiftTestingFramework

on:
  schedule:
    - cron:  '0 * * * *'

  workflow_run:
    workflows: ["Azure CI"]
    types:
      - completed
    branches: ['**']

  push: 
    paths:
      - '.github/workflows/run_tests.yml'
      - 'src/SwiftTestingFramework/*'

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  get-locations:
    runs-on: ubuntu-latest
    outputs: 
      matrix: ${{ steps.get-matrix.outputs.matrix }}

    steps:
    - uses: actions/checkout@v3

    - name: Read Locations
      id: get-matrix
      run: |
        content=`cat $GITHUB_WORKSPACE/location_matrix.json`
          # the following lines are only required for multi line json
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
        echo "::set-output name=matrix::$content"

  build-and-test:
    needs: get-locations
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-locations.outputs.matrix) }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build with dotnet
      run: dotnet build ${{ env.FRAMEWORK_PROJECT_PATH }} --configuration Release -p:Location=${{ matrix.location }}

    - name: Test with dotnet
      run: dotnet test ${{ env.FRAMEWORK_PROJECT_PATH }} --no-build --configuration Release --logger "trx;LogFileName=test-results.trx"

    - name: Test Report
      uses: phoenix-actions/test-reporting@v8
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: MSTest Results (${{ matrix.location }})  # Name of the check run which will be created
        path: ${{ env.FRAMEWORK_PROJECT_PATH }}/TestResults/*.trx  # Path to test results
        reporter: dotnet-trx